"""initial schema

Revision ID: f49cb6d52010
Revises: 
Create Date: 2026-06-13 15:33:35.572070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49cb6d52010'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('exerciser', 'trainer', 'admin', name='role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='accountstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('assigned_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exerciser_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('body_part', sa.Enum('chest', 'back', 'legs', 'shoulders', 'arms', 'core', name='bodypart'), nullable=False),
    sa.Column('exercise', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exerciser_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assigned_workouts_exerciser_id'), 'assigned_workouts', ['exerciser_id'], unique=False)
    op.create_table('cardio_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exerciser_id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.Enum('running', 'cycling', 'swimming', 'rowing', 'walking', 'elliptical', name='cardioactivity'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exerciser_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cardio_logs_exerciser_id'), 'cardio_logs', ['exerciser_id'], unique=False)
    op.create_table('exerciser_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Enum('weight_loss', 'muscle_gain', 'general_fitness', 'endurance', name='goal'), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('trainer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.Enum('strength_training', 'cardio_weight_loss', 'bodybuilding', 'crossfit', 'yoga_mobility', name='specialty'), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('approval_status', sa.Enum('pending', 'approved', name='approvalstatus'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exerciser_id', sa.Integer(), nullable=False),
    sa.Column('body_part', sa.Enum('chest', 'back', 'legs', 'shoulders', 'arms', 'core', name='bodypart'), nullable=False),
    sa.Column('exercise', sa.String(length=120), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exerciser_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_exerciser_id'), 'workouts', ['exerciser_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workouts_exerciser_id'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_table('trainer_profiles')
    op.drop_table('exerciser_profiles')
    op.drop_index(op.f('ix_cardio_logs_exerciser_id'), table_name='cardio_logs')
    op.drop_table('cardio_logs')
    op.drop_index(op.f('ix_assigned_workouts_exerciser_id'), table_name='assigned_workouts')
    op.drop_table('assigned_workouts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
